; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
monitor_filters = direct
build_unflags = 
    -Werror=all
    -Werror=maybe-uninitialized
build_flags = 
    -Wno-error=maybe-uninitialized
        -DEI_CLASSIFIER_DSP_TYPE=EI_CLASSIFIER_DSP_ESP32
    -DESP_PLATFORM
