/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 12.07.2026 10:51:38

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 10128;
#else
constexpr int kTensorArenaSize = 9104;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,3960 } };
const TfArray<1, float> quant0_scale = { 1, { 0.00390625, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 99, 40, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 99, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 50, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 50, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[7] = { -2503, 1185, 4653, 5183, -938, 1816, -5603, };
const TfArray<1, int> tensor_dimension6 = { 1, { 7 } };
const TfArray<1, float> quant6_scale = { 1, { 8.4093073382973671e-05, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[7*400] = { 
  26, 4, -75, 5, -51, -14, 4, -49, 33, 8, 5, 52, 2, -25, 21, -33, 9, -14, -67, 14, -47, 1, -3, -62, 18, 3, 9, 18, 2, -23, 12, -48, 19, -24, -55, 10, -92, 12, -9, -48, 21, 1, 14, 30, 4, -25, 18, -97, 20, 1, -43, 0, -87, 4, 0, -36, 19, -6, 8, 31, -3, -23, 27, -75, 19, -27, -39, -8, -73, 9, 10, -24, 8, 15, 22, 33, -5, -10, 23, -62, 7, -10, 6, -8, -42, 2, 2, -35, 16, 2, 24, 18, 1, -45, 18, -23, -4, 14, -21, -2, -32, 2, 5, 2, -1, -4, 9, 16, 0, -42, -7, -12, 22, -11, -60, -15, -58, 5, 1, -44, 15, -3, 13, 40, -10, -47, 19, -54, 4, -20, -56, 0, -50, 10, 12, -48, 3, 12, 20, 34, -1, -26, 2, -54, 4, -7, -46, 47, -62, 15, -9, -26, 20, 3, -2, 15, -5, -26, 16, -54, 19, -4, -71, 11, -90, 2, -12, -28, 6, 2, 7, 14, 5, -53, 11, -46, 15, -11, 20, 6, -78, 29, 8, -32, 5, 5, 19, 16, 14, -78, 5, -62, 7, -11, 45, 17, -84, 21, 14, 8, 17, -9, 25, 23, 8, -36, 16, -49, 8, -9, 22, 3, -63, 25, -3, -3, 10, -7, 23, 19, 15, -27, -3, -45, 21, -4, 31, 19, -74, 36, -12, -11, 18, -24, 23, 25, 5, -24, 10, -60, 10, 2, 17, -26, -79, 34, -22, -23, 20, -9, 8, 21, 7, -32, 19, -75, 24, 1, 7, -13, -52, 21, -11, -19, 8, -11, 10, 25, 3, -31, 24, -52, 25, -13, 19, -12, -66, 29, -8, -25, 10, 17, 10, 22, 8, -46, 6, -50, 28, -19, 28, -5, -71, 12, -7, -17, 7, -7, -5, 18, -3, -47, 19, -40, 9, -10, 4, -9, -60, 0, -12, -28, 20, 1, 1, 22, 4, -43, 12, -52, -3, -12, 9, -10, -73, 7, 4, -34, 29, -3, 5, 32, 10, -22, 9, -56, 13, -35, 6, 20, -84, 7, -3, -15, 15, 5, 15, 34, -2, -14, 24, -58, 19, -29, 8, 28, -71, 6, -1, -12, 13, 29, 25, 32, 13, -31, 8, -53, 35, -24, 14, 19, -95, 20, 7, -31, 19, 22, 15, 34, 9, -26, 17, -74, 18, -49, -13, 1, -86, 7, -10, -42, 34, 15, 15, 35, 2, -27, 24, -57, 
  -10, 23, 8, -8, -21, 11, -85, 7, -20, -40, -80, -67, 2, -50, -63, 11, -4, 6, 15, 22, 12, 8, -34, 11, -32, -7, -47, -78, 6, -23, -72, 10, 3, 14, 11, 3, 7, -12, -19, 17, -15, -16, 4, -61, -3, 27, -58, 40, -37, 11, 15, -3, 17, -6, -3, 5, -6, 3, -31, -38, -14, 21, -78, 34, -30, -1, 9, 11, 16, 7, -21, 10, -27, 2, -54, -46, 9, -1, -52, 4, -23, 10, 19, 25, 3, 1, -11, 8, -29, -11, -49, -38, 5, -10, -61, 7, -12, -2, 8, -2, 8, 6, 15, 7, -3, -8, 4, -1, -6, -23, -22, 0, -26, 13, 15, -2, 9, -7, 3, 16, -42, -2, -34, -59, 5, -61, -69, 2, 27, 19, 3, -6, -5, 0, 2, 5, -41, 15, -17, -43, 22, -14, -26, 15, 13, -22, 3, -17, 15, -5, 20, 10, -20, 37, 14, -3, 10, -14, 28, -3, -40, -17, 1, -7, -4, -8, -8, 9, -13, 7, -2, 13, 0, 12, 8, -13, -15, 0, -14, -2, 17, -12, -6, -10, 15, -16, 9, 16, -20, 24, 16, -1, 4, 40, -19, -48, 13, 4, -3, 2, -2, -3, 14, 9, -25, 32, -3, 15, -15, 23, -4, -21, 4, -11, 9, 5, -5, 13, 7, 6, 14, 24, -5, -1, -33, 9, 0, -43, 2, -18, -19, -4, -26, 11, -21, -5, -38, 57, -14, 3, -74, -32, -2, -4, 13, -10, 3, -5, -22, 8, -13, -15, -13, 49, -29, 7, -58, -23, 11, 1, 30, 5, 17, 8, -12, 23, -6, -8, -35, 89, -42, 14, -38, -2, 14, -35, 30, 27, 17, 5, -26, 2, 13, -44, -51, 47, -87, 16, -18, 11, 6, -16, 12, 10, 5, -5, -7, -13, -5, -51, -12, 48, -55, 15, 13, 19, -8, -16, 31, 12, -24, -3, -28, -13, 6, -49, -18, 20, -21, 24, -13, 6, 2, -24, 27, 10, -1, -6, -46, -29, 8, -51, -17, 38, -28, 25, -19, 14, 11, -85, 23, 6, -25, 10, -29, -5, -5, -99, -51, 32, -71, 30, -26, 20, 14, -87, 32, 13, -42, 5, -18, -11, -7, -63, -56, -48, -87, 26, -28, 10, 20, -46, 17, 24, -42, 23, -14, -19, -21, -41, -13, -49, -28, 1, -11, 19, 12, -43, 4, 21, 28, 10, -9, 6, -54, -34, -4, 8, -62, 10, 
  5, 4, 5, -16, -25, 3, -11, 16, -22, 17, 2, 25, -7, -2, 3, -13, 1, 6, 5, 11, -47, 7, -32, 2, -8, -17, -9, -1, 7, 1, 17, -31, 44, 15, -2, 23, -47, -1, -40, 6, 1, -11, -22, -2, 22, 6, 30, -32, 31, 16, 11, 26, -24, 1, -36, 6, -9, -25, -26, -12, 22, 40, 24, -15, 36, -1, 11, 1, -6, 9, -33, 3, -18, -10, -9, 0, 14, 23, 26, -40, 4, 15, 8, 10, -10, 10, -52, 6, -1, -30, -7, 4, 12, 66, 18, -24, -8, 9, 0, 58, 2, 9, -17, 9, -12, -5, -27, 22, -2, 24, -1, -5, 27, 5, -6, 9, -23, 25, -54, -12, -20, -15, -27, -7, 9, 32, 22, -31, 24, 12, 16, 8, -12, 11, -33, 11, -22, -22, -30, 8, 16, 33, 15, -31, 24, 15, 4, 12, -8, 9, -25, -10, -15, -28, -23, -7, 21, 32, 16, -35, -15, -41, 3, 2, -21, 36, -20, -22, -10, 17, -33, 3, -9, 53, -10, -35, -1, 11, 21, 21, -8, 51, -34, 4, -25, 7, -58, -5, 17, 45, -2, -36, 2, -4, -5, 6, -11, 9, -34, -15, 1, 6, -54, -9, 18, 46, 12, -18, -2, -17, -5, 15, -1, 16, -39, -6, -10, 4, -41, -7, 43, 45, 3, -9, 1, -13, -4, 17, 15, 29, -36, -16, 0, -1, -44, -7, 30, 41, -13, 11, 0, -21, 9, -2, 8, 26, -17, -29, -1, 25, -39, -12, 18, 33, -2, -7, 10, -9, 3, -8, 8, 9, -8, -7, -9, 26, -36, 4, 3, 29, 7, -11, 25, -6, 5, 3, -15, 12, 2, -5, -19, 20, -7, 1, 12, 22, 22, -15, 15, 1, 5, -12, -23, 17, -4, 2, -10, 8, -15, 9, -6, 12, 18, -26, 14, 4, 8, -1, -5, 2, 17, 0, -15, 13, 3, -2, 8, 25, 27, -14, 9, 12, 2, 4, -7, 14, 14, 7, -18, 15, -3, 6, 11, 26, 13, -15, 26, 3, 15, -8, -32, 18, 14, -3, -33, 2, 1, 7, 6, 11, 18, -20, 32, 16, 15, -24, -26, 20, 15, -6, -22, 13, 22, -12, 15, -9, 27, -18, 35, 13, 15, -25, -39, 15, 1, -6, -31, -1, 11, -18, 22, 10, 27, -16, 28, 19, 17, -38, -44, 29, -20, 3, -59, -11, 3, -19, 16, -13, 8, 7, 
  10, -26, -22, 48, 61, -3, -7, -36, 20, -36, 11, 0, 55, 19, -33, 20, 14, 20, -13, 22, 48, -11, 2, -18, 29, -78, 41, 3, 27, -5, -30, 39, 27, 16, -62, 21, 64, 12, -8, -39, 22, -68, 34, -6, 33, -5, -15, 61, 13, 15, -57, 24, 39, -5, -37, -47, 7, -51, -7, 2, 33, -8, -20, 36, 37, 29, -55, -3, 40, 27, -38, -30, 10, -70, -20, 2, 28, -47, -32, 57, 4, 23, -9, -30, 58, -2, 0, -12, -8, -55, 2, -17, 27, -86, -25, 31, -1, 20, 4, -9, 19, 4, -38, 21, -6, -37, 9, 4, -10, -53, -22, 24, 23, 34, -46, -6, 29, -26, -46, -44, -5, -76, -39, -12, 16, -31, -20, 35, 13, 4, -65, -1, 34, -22, -21, -49, 23, -39, -19, 5, 30, 5, -7, 30, -4, -27, -68, 3, 38, -5, 19, -18, -2, -18, 12, -2, 11, 10, -16, 27, -40, -5, 18, -3, 18, -3, -11, 34, -35, -34, -4, 8, -1, -15, -37, 31, -8, 54, 10, 5, 21, -21, 2, 32, -36, -3, 12, -16, 3, -37, -63, 26, 4, 17, -36, -2, 16, -25, 17, 6, -30, 19, 5, -41, 10, -34, -61, 17, 10, -30, -43, -8, 5, -39, -11, 2, -39, -14, 12, -27, 0, -25, -44, 11, 14, -3, -31, 5, 9, -11, 10, 27, -72, -10, 10, -1, -19, -32, -41, 30, 19, 6, -35, 21, 24, -22, -5, 36, -79, -28, 19, -23, 21, -52, -71, 23, 25, 19, -19, 41, 13, 7, -7, -10, -87, -40, 12, -7, 21, -54, -70, 23, 18, 30, -16, 33, 15, -27, -17, 23, -72, -49, 8, -10, 13, -40, -54, 26, 28, 8, -22, 26, 28, -31, -7, 12, -40, -66, 9, -7, 23, -31, -49, 22, 6, 13, -22, 27, 43, -32, -13, -1, -14, -48, 1, -37, 9, -41, -80, 39, 19, 3, -16, 23, 39, -46, 0, -11, 11, -30, 4, 4, 11, -18, -67, 37, 34, -20, -76, 49, 41, -59, -30, -23, 10, -60, 0, 7, 25, 10, -65, 31, 24, -16, -118, 57, 44, -47, -37, -27, 2, -62, -2, 31, 22, 17, -41, 26, 33, -37, -111, 57, 40, -46, -21, -35, 8, -48, 5, 6, 13, 20, -53, 29, -3, -68, -116, 92, 74, -66, -8, -38, -15, -15, -4, -11, 52, 44, -42, 48, 
  -42, 1, 16, -12, -25, 7, -14, 8, 23, 7, -43, -7, -22, 5, 0, -7, -26, 16, 8, -4, -10, 5, -12, 13, -11, 17, -46, 7, -1, 23, -32, 6, -32, 22, 4, -16, 4, 22, 1, 16, -16, -4, -32, -30, -8, -8, -30, 12, -38, 14, 18, -8, -7, -13, -21, 12, 1, -9, -52, -4, -5, -2, -30, -8, -15, 28, 21, 18, 19, 22, -44, 14, -8, -15, -32, -20, -4, 16, -49, 33, -8, 31, 11, 9, 20, 11, 26, 15, 5, 5, 6, -35, -22, 8, -14, 18, -1, -13, 0, 25, -15, 5, 6, 7, 18, 21, -13, 0, 28, 56, 23, -2, -20, 16, 18, -7, 10, 25, -47, 16, 10, 2, -29, -19, -17, 25, -17, 0, -9, 23, 32, -17, -9, 2, -23, 12, 15, -13, -38, -24, -29, 31, -24, 0, -5, 56, 30, 13, -6, -28, -59, 23, 10, -8, -58, -44, -12, 38, -82, 18, 51, 16, -53, 26, 4, 17, 1, -57, 0, -4, 12, -37, -44, 48, -44, 33, -23, -71, -1, 6, 5, -17, 13, -4, -15, 20, -32, -2, -12, 63, -12, -10, -96, -77, 2, 18, -21, -25, -11, 30, 5, 37, -51, -6, 8, 79, -9, -36, -15, 4, -23, 43, -18, -57, -7, 38, -17, -2, -47, 1, 13, 38, -1, -23, -55, -73, -18, 27, -4, -61, 15, -18, 20, -6, -27, 8, 13, 57, -32, -13, -80, -6, 9, 31, -24, 8, -21, 14, 31, 26, -75, 6, 37, 52, -22, -31, -63, -24, 0, 20, -3, -6, -26, -2, 29, 27, -57, -18, 32, 52, -22, -1, -58, -59, -8, 44, -6, -28, 27, -10, 20, 39, -16, -6, 36, 26, -38, 18, -13, 4, -3, 27, -1, 1, 1, 0, 37, -2, -10, -16, 30, 2, -23, 0, -23, 28, 11, 24, -35, 14, -45, 18, 13, -32, -59, -41, 27, 7, -23, -25, -19, 30, 12, 47, -31, 3, -49, 14, 15, -1, -127, -8, 46, 15, -23, -13, -50, 16, 4, 52, -6, 4, -35, 7, 29, -11, -85, -5, 35, 9, -11, -21, -26, 31, 8, 25, -37, 4, -80, 0, 17, 6, -117, -11, 12, 15, -27, -31, -24, 25, 14, 11, -18, 3, -62, 9, 31, 1, -100, 3, 8, 46, -22, -19, -37, 19, 11, 51, -8, 14, -54, 7, 22, -39, -54, 6, -7, 39, -40, 5, 
  -23, -12, 10, -23, 3, 8, 14, 13, -10, 19, -26, -3, -12, 27, -11, -3, -29, -9, 9, -33, 8, -11, 17, 8, 13, 9, -22, 5, 7, 27, 12, -4, -42, 24, -1, -7, 1, -3, 7, 12, -4, 4, -4, -12, 8, -8, -14, 0, -21, 18, 10, 9, -2, -11, 37, 10, 1, 7, 28, -15, 25, -16, 1, 22, -28, 15, 2, -6, -3, -19, 21, 2, 19, -1, -26, -23, 21, 32, -1, 4, -8, -19, -3, 1, -4, 2, 13, -8, 11, 9, 1, -24, 21, 59, 5, 5, 1, -2, -3, -15, 17, 1, 13, -5, -5, 26, 13, 15, 12, 22, 11, -2, -37, -13, -7, 15, 1, -12, 35, -11, 1, 32, 8, -8, 18, 28, 2, 10, -28, -6, -21, 0, 4, -17, 22, -2, 12, 36, 18, -19, 23, 9, 8, 16, -20, -28, -42, 3, 5, -6, 26, -21, 20, 8, 19, -27, 17, 19, 14, 11, -16, 11, -11, -6, -2, 9, 7, -9, 8, -17, 22, -20, 33, 17, 2, 0, -23, 19, -10, -12, 6, -37, 10, 15, 21, -5, -2, -18, 23, 14, 8, 4, -1, 23, -13, -16, 11, -7, 20, 6, 9, 7, 9, -10, 23, -6, 10, 11, -1, -2, 18, -25, 12, -7, 27, 3, 17, 14, 15, -15, -6, 0, 3, 8, 9, 33, 26, -10, 5, -8, 27, 22, 24, -2, 22, -5, 3, 8, 14, 7, 31, 50, -4, -16, 12, -17, 26, 9, 16, 3, 23, -31, 4, 12, 25, 6, 6, 33, -21, -33, 13, -31, 18, -10, 22, -10, 7, -10, 8, 9, 18, 10, -10, 24, -45, -33, 1, -35, -7, -27, 13, -12, -5, -2, 6, 50, 15, 0, -23, 1, 0, -32, -21, -3, 8, -46, 11, 3, -6, -7, -6, 55, 15, -14, -14, -2, -22, -53, -15, -15, 32, -37, 4, 15, 16, -14, -9, 48, 22, -7, -13, -8, -21, -52, -4, 15, 6, -40, 5, 28, 19, -5, -23, 53, 11, 0, 17, 14, 6, -60, 8, 21, 11, -19, 1, 13, 10, -11, -18, 57, 6, 13, 5, 21, 6, -39, 7, 16, 15, -11, 21, -9, 14, -16, -8, 22, 18, 6, -1, 12, 14, -45, 2, 15, 2, 16, -4, -3, -15, -14, 9, 33, 4, 10, -19, 26, 9, -59, 5, 4, 16, 15, 5, -21, 0, -20, 10, -4, -4, -10, 
  21, -24, -6, -1, 51, -10, 50, -13, 19, 59, 25, -4, -8, 9, 12, 35, 21, -25, -4, -16, 25, -21, 40, -14, 9, 35, 23, 11, 1, -3, 13, 19, -16, -44, -4, -31, 22, -24, 52, -7, 9, 52, 28, 4, -26, -24, 8, 26, -13, -31, 3, -23, 7, -14, 30, -7, 6, 31, 0, 8, -33, -21, 6, 21, -16, -43, 6, -28, 16, -18, 48, -3, 4, 26, 23, 11, -39, -34, 5, 17, 6, -19, 1, -33, 21, 3, 49, 4, 8, 30, 11, 2, -30, -66, 15, 19, 2, 5, -4, -42, 1, -1, -6, -13, 10, 0, 3, 11, 1, -13, 0, 7, -18, -23, 23, -24, 15, -4, 35, 4, 6, 34, 25, 6, -33, -57, 11, 20, -42, -26, 37, -9, 24, 4, 26, 26, 12, 15, 29, 8, -35, -59, -10, 32, -33, 26, 50, -28, 10, -15, 15, 42, 12, 6, -14, -8, -32, -78, 15, 25, 19, 40, 20, -23, 7, -31, 4, 1, 3, 6, 11, 0, -46, -94, 7, 28, 3, 12, -16, -30, 21, -27, 25, -33, 6, 1, 26, -11, -34, -80, 2, 18, -2, -18, -34, -10, 21, -32, 14, -34, 18, 1, 17, -4, -36, -54, 16, 21, -6, -17, -4, -13, 22, -21, 10, -21, 4, 0, 17, -8, -45, -59, 0, 30, 18, 25, -21, -22, 18, -19, 8, 11, 15, -7, 18, -1, -22, -83, 15, 14, 19, 34, -22, 4, 14, -16, 13, 21, 10, -2, 16, 0, -23, -67, 9, 18, -1, 35, -35, 8, 10, -15, 5, 45, 14, -7, 1, 20, -25, -64, 12, 14, -2, 24, -62, 9, 4, -34, -5, 13, 12, 12, 7, 18, -27, -42, 12, 13, -2, 13, -52, 22, 15, -24, 18, 42, 16, 25, 9, 6, -11, -79, 18, 30, -10, 2, -12, 0, 15, -34, 11, 46, 17, 10, 9, 10, -4, -65, 8, 29, -33, -5, 1, 12, 10, -24, 20, 41, 7, 22, 4, 15, 1, -66, 9, 21, -22, -11, -10, 14, 19, -63, 25, 21, 2, 18, 7, 19, -2, -48, 2, 13, -22, -26, -6, 12, 13, -71, 22, 8, 13, 29, 21, 18, 7, -37, 5, 14, -9, -34, -8, 16, 11, -57, 24, 0, 6, 40, 23, 22, -12, -30, -3, 25, -14, -21, -6, 6, 35, -22, 26, 2, 10, 38, 20, 33, -31, -15, 4, 19, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 7,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0086439037695527077, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -639, -3200, -5509, -10693, -55, -4324, 935, -10142, 164, 5173, -2602, -306, -1146, 3108, 933, 735, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 0.00019946278189308941, 0.00011115106462966651, 5.1705119403777644e-05, 6.0333797591738403e-05, 9.6629439212847501e-05, 5.1944942242698744e-05, 0.00016185984713956714, 5.9848811361007392e-05, 0.00016839720774441957, 0.00012084925401723012, 0.00011528197501320392, 0.00012781587429344654, 0.00010889812256209552, 0.00014963035937398672, 0.00018760754028335214, 6.8804059992544353e-05, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ 1,24,28,3,-85,4,-7,-64, 1,22,-45,-1,-118,2,1,-96, 1,24,19,0,-127,-22,-1,-59, 
  /* [1][0][][] */ -11,32,25,-2,-6,24,9,-16, -7,27,34,-4,10,42,5,-37, -21,20,-56,-11,-127,-28,15,-96, 
  /* [2][0][][] */ -11,13,14,-23,110,11,-27,26, -11,20,33,2,47,-9,-18,114, -17,8,10,-34,127,-29,11,29, 
  /* [3][0][][] */ 116,-5,-85,-20,-114,-14,23,-68, -13,-15,-110,-43,-127,19,12,-17, 54,-31,-47,-11,-48,29,-25,-53, 
  /* [4][0][][] */ 13,-8,-14,-106,-57,-77,63,-84, 6,-8,-9,-127,-59,-44,12,-87, 20,-12,8,-113,12,-41,63,-7, 
  /* [5][0][][] */ -97,80,25,-2,-58,-86,-36,-41, -55,30,17,-24,53,-17,-41,-8, -50,127,123,-3,20,-1,-63,6, 
  /* [6][0][][] */ -41,27,-56,-12,-127,-105,24,-46, -61,0,-40,-20,-90,-57,4,-21, -47,14,-95,-16,-105,-61,14,-63, 
  /* [7][0][][] */ 17,31,17,-20,-19,33,33,13, 12,25,3,-22,127,43,-7,17, 19,47,-36,-3,-56,27,25,-33, 
  /* [8][0][][] */ 5,-33,-60,25,-61,5,-71,-29, 8,-42,-127,-7,-29,16,-98,-4, 2,-33,-73,22,-40,10,-87,-32, 
  /* [9][0][][] */ -33,-20,-106,-11,-103,-40,-2,-19, -127,-4,5,-13,-84,-32,1,-14, -35,-18,-46,-8,-90,-11,-12,-17, 
  /* [10][0][][] */ -33,40,-94,2,-116,-127,21,-102, -35,58,2,-9,-73,-115,2,-50, -10,43,-61,0,-23,-70,35,-70, 
  /* [11][0][][] */ 0,27,-52,39,-80,-72,-22,-80, -2,13,-45,-3,-69,-67,-5,-33, -2,4,-84,27,-127,-117,-7,-85, 
  /* [12][0][][] */ -9,20,5,-4,-88,54,-3,-87, 31,0,-5,-7,-127,11,-21,-101, 6,-3,-9,-4,-110,21,-29,-83, 
  /* [13][0][][] */ 9,-91,-11,-16,-16,-20,-16,1, 15,-98,-62,-15,-74,-77,-22,-58, 1,-127,-50,-21,-51,-82,-14,-39, 
  /* [14][0][][] */ -13,6,-12,10,-120,0,-18,-106, -15,13,7,-3,-127,15,-23,-83, -13,6,-8,14,-115,14,-20,-105, 
  /* [15][0][][] */ -3,5,29,-84,7,-21,90,-7, -9,26,12,-91,-10,-31,-23,-30, -15,3,13,-83,-127,-40,87,-106, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.012182589620351791, 0.0067887743934988976, 0.0031579937785863876, 0.0036850078031420708, 0.0059018367901444435, 0.0031726416200399399, 0.0098859146237373352, 0.0036553861573338509, 0.010285196825861931, 0.0073811104521155357, 0.0070410780608654022, 0.0078066112473607063, 0.0066511714830994606, 0.0091389743611216545, 0.011458506807684898, 0.0042023458518087864, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { -21639, 282688, 144631, 26560, 237440, 123901, 16878, 115863, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 1.3370747183216736e-05, 6.1986088439880405e-06, 1.1013257790182251e-05, 1.6105421309475787e-05, 7.8343164204852656e-06, 1.1972710126428865e-05, 2.2185156922205351e-05, 1.3278184269438498e-05, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*40] = { 
  /* [0][0][][] */ -27,3,-16,-28,-75,1,24,-19,-58,-105,-49,-116,-46,-20,-47,-31,-31,-36,-37,-35,-23,-8,-1,-10,2,17,-12,-13,10,49,42,63,83,127,101,50,64,76,106,96, -30,-4,-20,-9,-74,-5,15,-8,-60,-89,-63,-80,-44,-8,-52,-23,-9,-15,-37,-27,-23,-21,10,-27,27,4,-12,-17,38,42,51,36,64,102,89,43,76,84,82,101, -16,2,-7,-25,-59,0,34,-10,-68,-103,-42,-103,-61,-38,-33,-53,-6,-42,-40,-28,-9,-9,24,-23,10,13,4,-25,21,56,70,37,82,115,88,70,48,97,106,125, 
  /* [1][0][][] */ -35,-16,10,50,45,49,24,-31,-39,-23,8,30,-8,29,69,79,53,80,43,-28,-29,-103,0,-41,-34,-99,-127,-66,-33,2,-42,-46,-57,-14,-56,-25,-40,-50,22,29, -16,-23,-8,-51,73,60,61,-21,-39,-85,48,-75,-24,-1,-6,80,68,26,-28,-5,-48,10,-43,-63,-62,-117,-59,-114,-33,-20,-41,-91,-28,-6,-35,-79,-99,0,-39,-64, 1,1,30,4,7,99,93,-11,-18,5,-16,38,11,16,67,45,67,95,50,-62,-113,-72,-52,-58,-52,-71,-117,-52,-29,-31,-64,-63,-31,-25,-32,-47,29,-17,46,46, 
  /* [2][0][][] */ -34,127,-24,-47,-84,-77,-66,-56,-74,-30,-87,64,-62,-112,-63,-3,38,58,23,-8,0,5,45,78,42,33,15,-79,36,-55,11,36,-10,0,-7,-34,-22,-50,-25,-102, 5,51,-91,2,-55,-40,-86,-115,-100,-8,75,-44,-86,-84,-29,31,34,-24,36,35,1,65,-2,6,-67,48,-75,46,-1,-24,-23,-31,-71,0,-32,-21,-6,-65,-96,-31, -34,4,-34,-51,-41,60,-56,-114,32,-62,-29,-90,39,7,-70,-50,-49,-65,35,-62,2,-34,54,53,80,-117,11,-36,36,22,13,-41,46,-94,35,15,-70,-26,-70,-72, 
  /* [3][0][][] */ -40,-113,-119,-127,-34,-6,54,34,51,22,30,1,53,82,77,73,65,48,34,-20,-15,-14,8,1,5,-15,-43,-39,-21,7,-5,-27,-6,-3,-19,-61,-46,-20,-19,22, -46,-97,-95,-92,-16,-3,42,8,56,41,6,9,37,65,75,60,44,65,20,-13,0,-31,-6,-6,4,-51,-46,-38,-27,1,-6,-15,-11,-3,-13,-65,-41,-25,2,10, -51,-102,-119,-110,-30,-5,45,24,24,33,42,3,40,90,66,71,57,49,17,-6,-37,-24,-10,-22,-16,-38,-35,-17,-15,-13,-2,-38,-15,-1,-26,-45,-41,-26,-22,19, 
  /* [4][0][][] */ -63,-66,-59,-29,-69,-78,-40,-29,-78,-56,-18,-76,-58,-36,-8,49,-51,-55,-46,-70,-68,-79,-54,-60,-19,-55,-70,-71,-40,-85,21,-14,31,37,17,11,-48,28,-2,-3, -21,-28,15,-20,-55,-116,-50,-47,26,-112,-59,-37,-34,-94,-24,-110,-33,-26,-2,-53,-57,-38,-21,-23,-25,-9,-77,-16,-33,-90,-37,16,-52,-35,-13,6,35,-67,-44,-12, -34,-11,-44,-24,-20,-21,-77,15,-91,-64,-57,-93,-68,-43,-110,34,-56,-54,-127,-45,-27,-83,-111,-78,-25,-24,-52,-29,-47,-41,-37,-34,60,-2,35,6,-5,35,23,35, 
  /* [5][0][][] */ -83,-75,-124,-78,-65,-90,-100,-27,-38,-28,-81,-4,21,-27,-81,-9,-66,-11,-54,7,20,-8,16,9,52,7,-6,51,16,47,22,48,-5,22,-12,21,-26,-10,-17,45, -63,-127,-109,-102,-82,-54,-87,-59,-76,-85,-42,-39,-15,-38,-72,-44,-6,-64,-3,0,18,-11,-6,46,21,36,10,10,14,50,27,33,10,32,15,-20,40,35,54,1, -30,-110,-64,-107,-57,-102,-98,-71,3,-10,-33,-9,-35,-68,-17,-21,14,-58,-87,-3,-24,27,56,-3,-12,51,27,60,58,16,39,8,1,3,-25,39,8,12,-5,75, 
  /* [6][0][][] */ 44,78,123,127,70,39,22,2,-14,-51,-39,-31,-27,-28,-14,-21,-32,-32,-28,-20,-15,-4,-17,-12,-10,-18,-4,-5,-1,-9,-17,-8,-2,-2,-1,-9,-14,0,-4,-6, 46,81,118,112,63,42,26,19,-21,-38,-31,-30,-32,-6,-2,-13,-24,-41,-34,-17,-15,-12,-13,-12,-12,-6,1,5,-3,-25,-13,-2,-2,-9,-7,-4,-4,-16,-12,-3, 50,93,116,121,59,42,26,1,-12,-46,-45,-38,-34,-27,-11,-12,-31,-35,-35,-22,-13,-13,-15,-4,-12,-17,-11,-11,-6,-13,-26,-9,3,-2,-6,-13,-20,-11,-4,-14, 
  /* [7][0][][] */ -39,-107,-25,-42,-10,-48,-57,-21,-32,-35,-35,-62,-1,-109,-56,-77,-17,-51,-24,19,-24,-5,-32,-44,-25,-47,-2,-37,26,0,13,-18,29,35,-11,-13,21,30,48,-13, -35,-68,-47,-21,-20,-28,-8,-17,-91,-9,-32,-33,-23,-38,-38,-16,10,-38,-58,-32,-57,-24,26,-54,-11,-39,-7,-49,-68,-24,-55,22,-19,-2,62,36,11,23,-3,17, 21,-33,-6,-42,-54,-65,-19,-127,-89,-40,-38,-44,-50,-33,-15,-64,-68,2,-32,-37,-86,-56,-46,4,-68,12,4,-24,-13,37,2,29,-15,25,-3,82,49,-25,27,-7, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,40 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0034229112789034843, 0.0015868438640609384, 0.0028193939942866564, 0.0041229878552258015, 0.002005585003644228, 0.0030650137923657894, 0.0056794001720845699, 0.0033992151729762554, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,99,40 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,99,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.016372773796319962, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,99,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,50,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,50,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,50,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.009728599339723587, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,50,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,7 } };
const TfArray<1, float> quant21_scale = { 1, { 0.14502601325511932, } };
const TfArray<1, int> quant21_zero = { 1, { 37 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension0, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 28, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 2800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension13, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension15, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension17, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 7, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 7, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1034060_6_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1034060_6_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1034060_6_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1034060_6_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1034060_6_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
